// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8N8gQsSPXXzKkrb1xG3pa0wB9ZNJ4o9I',
    appId: '1:776212626361:web:3b40935a8035da24c8d468',
    messagingSenderId: '776212626361',
    projectId: 'yash-task',
    authDomain: 'yash-task.firebaseapp.com',
    storageBucket: 'yash-task.firebasestorage.app',
    measurementId: 'G-P2YPH8XT30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHCL3a7Y1uNyn0tU8ec17cvHRguRDYH1M',
    appId: '1:776212626361:android:ab563044be4937c4c8d468',
    messagingSenderId: '776212626361',
    projectId: 'yash-task',
    storageBucket: 'yash-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIM2mo0dDReV-jpdfSQIdNsI6EPivAOA4',
    appId: '1:776212626361:ios:78045109778c9c8bc8d468',
    messagingSenderId: '776212626361',
    projectId: 'yash-task',
    storageBucket: 'yash-task.firebasestorage.app',
    iosBundleId: 'com.example.yashPratical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIM2mo0dDReV-jpdfSQIdNsI6EPivAOA4',
    appId: '1:776212626361:ios:78045109778c9c8bc8d468',
    messagingSenderId: '776212626361',
    projectId: 'yash-task',
    storageBucket: 'yash-task.firebasestorage.app',
    iosBundleId: 'com.example.yashPratical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8N8gQsSPXXzKkrb1xG3pa0wB9ZNJ4o9I',
    appId: '1:776212626361:web:13c72cf284fda440c8d468',
    messagingSenderId: '776212626361',
    projectId: 'yash-task',
    authDomain: 'yash-task.firebaseapp.com',
    storageBucket: 'yash-task.firebasestorage.app',
    measurementId: 'G-D61V8E0VB3',
  );
}
